# Generated by Django 3.2 on 2021-10-02 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SliderTop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_title', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Slider top',
                'verbose_name_plural': 'Sliders top',
            },
        ),
    ]
