# Generated by Django 3.2 on 2021-10-02 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_slidertop_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kategori', models.CharField(help_text='Field ini tidak boleh dikosongkan', max_length=200)),
                ('fa_class', models.CharField(help_text='Field ini tidak boleh dikosongkan', max_length=50)),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategori',
            },
        ),
    ]
