# Generated by Django 3.2 on 2021-10-02 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_kategori'),
    ]

    operations = [
        migrations.AddField(
            model_name='kategori',
            name='slug',
            field=models.SlugField(default=1, help_text='Field ini terisi secara otomatis', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
