# Generated by Django 3.2 on 2021-10-02 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_kategori_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iklan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_iklan', models.CharField(help_text='Field ini tidak boleh dikosongkan.', max_length=200)),
                ('slug', models.SlugField(help_text='Field ini akan terisi secara otomatis.', max_length=100, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='iklan/images')),
                ('kategori_iklan', models.ForeignKey(help_text='Pilih kategori. Field ini tidak boleh dikosongkan.', on_delete=django.db.models.deletion.CASCADE, to='main.kategori')),
            ],
            options={
                'verbose_name': 'Iklan',
                'verbose_name_plural': 'Iklan',
            },
        ),
    ]
