# Generated by Django 3.2 on 2021-10-02 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_iklan'),
    ]

    operations = [
        migrations.AddField(
            model_name='iklan',
            name='deskripsi_singkat',
            field=models.CharField(default=1, help_text='Field ini tidak boleh dikosongkan.', max_length=200),
            preserve_default=False,
        ),
    ]
