# Generated by Django 3.2 on 2021-10-02 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_iklan_deskripsi_singkat'),
    ]

    operations = [
        migrations.AddField(
            model_name='iklan',
            name='klasifikasi',
            field=models.CharField(choices=[('Terbaru', 'Terbaru'), ('Terpopuler', 'Terpopuler'), ('Trending', 'Trending')], default='Terbaru', help_text='Pilih klasifikasi iklan.', max_length=100),
        ),
    ]
